global using System.ComponentModel.DataAnnotations;
global using System.Text.Json;
global using Ater.Web.Core.Models;
global using Entity;
global using Share.Models;
global using System.Text;
global using Ater.Web.Core.Utils;
global using CodeGenerator.Helper;
global using Project = Entity.Project;
global using PropertyInfo = CodeGenerator.Models.PropertyInfo;
